name: Build release Docker image

on:
  push:
    tags:
    - v*

env:
  CONTAINER_REGISTRY: ghcr.io

jobs:
  build:
    name: Build and publish to registry
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Setup Node.js
      uses: actions/setup-node@v1

    - name: Compute variables
      id: vars
      run: |
        VERSION="${GITHUB_REF/refs\/tags\//}"
        VERSION_FULL="$VERSION-$(date +%s)"

        IMAGE_NAME="${{ github.repository }}"
        IMAGE_URL="${{ env.CONTAINER_REGISTRY }}/$IMAGE_NAME"

        echo "::set-output name=VERSION::$VERSION"
        echo "::set-output name=VERSION_FULL::$VERSION_FULL"
        echo "::set-output name=IMAGE_URL::$IMAGE_URL"

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        build-args: |
          NODE_AUTH_TOKEN=${{ github.token }}
        push: true
        tags: |
          ${{ steps.vars.outputs.IMAGE_URL }}:latest
          ${{ steps.vars.outputs.IMAGE_URL }}:commit-${{ github.sha }}
          ${{ steps.vars.outputs.IMAGE_URL }}:${{ steps.vars.outputs.VERSION }}
          ${{ steps.vars.outputs.IMAGE_URL }}:${{ steps.vars.outputs.VERSION_FULL }}
